# IMPORTING LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# IMPORTING DATASET

In [ ]:
data=pd.read_csv("/content/mobile_price.csv")

In [ ]:
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

# SPLITTING THE DATASET

In [ ]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

# NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred_train=gnb.predict(x_train)
y_pred_test=gnb.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

def report(x,y):
  print(confusion_matrix(x,y))
  print(accuracy_score(x,y))
  print(classification_report(x,y))

In [ ]:
print("Train Data")
report(y_train,y_pred_train)
print("Test Data")
report(y_test,y_pred_test)

Train Data
[[366  36   0   0]
 [ 27 292  72   0]
 [  0  71 297  38]
 [  0   1  45 355]]
0.81875
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       402
           1       0.73      0.75      0.74       391
           2       0.72      0.73      0.72       406
           3       0.90      0.89      0.89       401

    accuracy                           0.82      1600
   macro avg       0.82      0.82      0.82      1600
weighted avg       0.82      0.82      0.82      1600

Test Data
[[94  4  0  0]
 [16 80 13  0]
 [ 0 17 67 10]
 [ 0  0  4 95]]
0.84
              precision    recall  f1-score   support

           0       0.85      0.96      0.90        98
           1       0.79      0.73      0.76       109
           2       0.80      0.71      0.75        94
           3       0.90      0.96      0.93        99

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg 

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=45)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=45)

In [ ]:
y_pred_knn_train=knn.predict(x_train)
y_pred_knn_test=knn.predict(x_test)

In [ ]:
print("Train Data")
report(y_train,y_pred_knn_train)
print("Test Data")
report(y_test,y_pred_knn_test)

Train Data
[[394   8   0   0]
 [ 13 365  13   0]
 [  0  28 355  23]
 [  0   0  25 376]]
0.93125
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       402
           1       0.91      0.93      0.92       391
           2       0.90      0.87      0.89       406
           3       0.94      0.94      0.94       401

    accuracy                           0.93      1600
   macro avg       0.93      0.93      0.93      1600
weighted avg       0.93      0.93      0.93      1600

Test Data
[[97  1  0  0]
 [13 94  2  0]
 [ 0  3 85  6]
 [ 0  0  2 97]]
0.9325
              precision    recall  f1-score   support

           0       0.88      0.99      0.93        98
           1       0.96      0.86      0.91       109
           2       0.96      0.90      0.93        94
           3       0.94      0.98      0.96        99

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted av

# SVC

In [ ]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svc_train=svc.predict(x_train)
y_pred_svc_test=svc.predict(x_test)

In [ ]:
print("Train Data")
report(y_train,y_pred_svc_train)
print("Test Data")
report(y_test,y_pred_svc_test)

Train Data
[[402   0   0   0]
 [  0 386   5   0]
 [  0   3 401   2]
 [  0   0   2 399]]
0.9925
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       402
           1       0.99      0.99      0.99       391
           2       0.98      0.99      0.99       406
           3       1.00      1.00      1.00       401

    accuracy                           0.99      1600
   macro avg       0.99      0.99      0.99      1600
weighted avg       0.99      0.99      0.99      1600

Test Data
[[ 98   0   0   0]
 [  2 105   2   0]
 [  0   0  92   2]
 [  0   0   1  98]]
0.9825
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        98
           1       1.00      0.96      0.98       109
           2       0.97      0.98      0.97        94
           3       0.98      0.99      0.98        99

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       

# SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE
smp=SMOTE()

In [ ]:
x_smote,y_smote=smp.fit_resample(x,y)

In [ ]:
x_sm_train,x_sm_test,y_sm_train,y_sm_test=train_test_split(x_smote,y_smote,test_size=0.2,random_state=2)

# AFTER SMOTING

SVC

In [ ]:
svc.fit(x_sm_train,y_sm_train)

SVC(kernel='linear')

In [ ]:
y_pred_svm_train_sm=svc.predict(x_train)
y_pred_svm_test_sm=svc.predict(x_test)

In [ ]:
report(y_train,y_pred_svm_train_sm)
report(y_test,y_pred_svm_test_sm)

[[402   0   0   0]
 [  0 386   5   0]
 [  0   3 401   2]
 [  0   0   2 399]]
0.9925
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       402
           1       0.99      0.99      0.99       391
           2       0.98      0.99      0.99       406
           3       1.00      1.00      1.00       401

    accuracy                           0.99      1600
   macro avg       0.99      0.99      0.99      1600
weighted avg       0.99      0.99      0.99      1600

[[ 98   0   0   0]
 [  2 105   2   0]
 [  0   0  92   2]
 [  0   0   1  98]]
0.9825
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        98
           1       1.00      0.96      0.98       109
           2       0.97      0.98      0.97        94
           3       0.98      0.99      0.98        99

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg     

KNN

In [ ]:
knn.fit(x_sm_train,y_sm_train)

KNeighborsClassifier(n_neighbors=45)

In [ ]:
y_pred_knn_train_sm=knn.predict(x_train)
y_pred_knn_test_sm=knn.predict(x_test)

In [ ]:
report(y_train,y_pred_knn_train_sm)
report(y_test,y_pred_knn_test_sm)

[[394   8   0   0]
 [ 13 365  13   0]
 [  0  28 355  23]
 [  0   0  25 376]]
0.93125
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       402
           1       0.91      0.93      0.92       391
           2       0.90      0.87      0.89       406
           3       0.94      0.94      0.94       401

    accuracy                           0.93      1600
   macro avg       0.93      0.93      0.93      1600
weighted avg       0.93      0.93      0.93      1600

[[97  1  0  0]
 [13 94  2  0]
 [ 0  3 85  6]
 [ 0  0  2 97]]
0.9325
              precision    recall  f1-score   support

           0       0.88      0.99      0.93        98
           1       0.96      0.86      0.91       109
           2       0.96      0.90      0.93        94
           3       0.94      0.98      0.96        99

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.93      0.9

GNB

In [ ]:
gnb.fit(x_sm_train,y_sm_train)

GaussianNB()

In [ ]:
y_pred_gnb_train_sm=gnb.predict(x_train)
y_pred_gnb_test_sm=gnb.predict(x_test)

In [ ]:
report(y_train,y_pred_gnb_train_sm)
report(y_test,y_pred_gnb_test_sm)

[[366  36   0   0]
 [ 27 292  72   0]
 [  0  71 297  38]
 [  0   1  45 355]]
0.81875
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       402
           1       0.73      0.75      0.74       391
           2       0.72      0.73      0.72       406
           3       0.90      0.89      0.89       401

    accuracy                           0.82      1600
   macro avg       0.82      0.82      0.82      1600
weighted avg       0.82      0.82      0.82      1600

[[94  4  0  0]
 [16 80 13  0]
 [ 0 17 67 10]
 [ 0  0  4 95]]
0.84
              precision    recall  f1-score   support

           0       0.85      0.96      0.90        98
           1       0.79      0.73      0.76       109
           2       0.80      0.71      0.75        94
           3       0.90      0.96      0.93        99

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84 