# IMPORTING LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# IMPORTING DATASET

In [ ]:
data=pd.read_csv("/content/Mobile_data.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   clock_speed    2000 non-null   float64
 2   fc             2000 non-null   int64  
 3   int_memory     2000 non-null   int64  
 4   m_dep          2000 non-null   float64
 5   mobile_wt      2000 non-null   int64  
 6   n_cores        2000 non-null   int64  
 7   pc             2000 non-null   int64  
 8   px_height      2000 non-null   int64  
 9   px_width       2000 non-null   int64  
 10  ram            2000 non-null   int64  
 11  sc_h           2000 non-null   int64  
 12  sc_w           2000 non-null   int64  
 13  talk_time      2000 non-null   int64  
 14  price_range    2000 non-null   int64  
dtypes: float64(2), int64(13)
memory usage: 234.5 KB


In [ ]:
data.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

# SPLITTING THE DATASET

In [ ]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
np.sqrt(2000)

44.721359549995796

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=45)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=45)

In [ ]:
y_pred_train=knn.predict(x_train)
y_pred_test=knn.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
def report(x,y):
  print("Accuracy of the model : ",accuracy_score(x,y))
  print(confusion_matrix(x,y))
  print(classification_report(x,y))

  



In [ ]:
print("Training Dataset")
report(y_train,y_pred_train)
print("Testing Dataset")
report(y_test,y_pred_test)

Training Dataset
Accuracy of the model :  0.93125
[[394   8   0   0]
 [ 13 365  13   0]
 [  0  28 355  23]
 [  0   0  25 376]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       402
           1       0.91      0.93      0.92       391
           2       0.90      0.87      0.89       406
           3       0.94      0.94      0.94       401

    accuracy                           0.93      1600
   macro avg       0.93      0.93      0.93      1600
weighted avg       0.93      0.93      0.93      1600

Testing Dataset
Accuracy of the model :  0.9325
[[97  1  0  0]
 [13 94  2  0]
 [ 0  3 85  6]
 [ 0  0  2 97]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93        98
           1       0.96      0.86      0.91       109
           2       0.96      0.90      0.93        94
           3       0.94      0.98      0.96        99

    accuracy                           0.93       400
   

# VISUALIZING USING AN APP

In [ ]:
!pip install Gradio


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pickle
import gradio as gr

In [ ]:
with open('knn_model.pkl','wb') as f:
  pickle.dump(knn,f)

In [ ]:
x.columns


Index(['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep',
       'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h',
       'sc_w', 'talk_time'],
      dtype='object')

In [ ]:
def make_preds(battery_power, clock_speed, fc, int_memory, m_dep,
       mobile_wt, n_cores, pc, px_height, px_width, ram,sc_h,
       sc_w, talk_time):
  with open("knn_model.pkl",'rb') as f:
    clf=pickle.load(f)
    preds=clf.predict([[battery_power, clock_speed, fc, int_memory, m_dep,mobile_wt, n_cores, pc, px_height, px_width, ram,sc_h,sc_w, talk_time]])
  if preds==0:
    return("Low Cost")
  elif preds==1:
    return("Low-Medium cost")
  elif preds==2:
    return ("Medium-High cost")
  else:
    return("High Cost")

In [ ]:
battery_power=gr.Number(label="Enter Average battery power btw 501-2000 : ")
clock_speed=gr.Number(label="Enter Clock Speed btw 0.5-3 : ")
fc=gr.Number(label="Enter fc btw 0-19 : ")
int_memory=gr.Number(label="Enter int_mem btw2-64 : ")
m_dep=gr.Number(label="Enter m_dep btw 0.1-1 : ")
mobile_wt=gr.Number(label="Enter weight btw 80-200 : ")
n_cores=gr.Number(label="Enter cores btw 1-8 : ")
pc=gr.Number(label="Enter pc btw 0-20 : ")
px_height=gr.Number(label="Enter height btw 0-1960 : ")
px_width=gr.Number(label="Enter width btw 500-1998 : ")
ram=gr.Number(label="Enter ram 256-3998 : ")
sc_h=gr.Number(label="Enter sc_h btw 5-19 : ")
sc_w=gr.Number(label="Enter sc_w btw 0-18 : ")
talk_time=gr.Number(label="Enter talktime btw 2-20 : ")

op=gr.Textbox()

In [ ]:
app=gr.Interface(fn=make_preds,inputs=[battery_power, clock_speed, fc, int_memory, m_dep,mobile_wt, n_cores, pc, px_height, px_width, ram,sc_h, sc_w, talk_time],outputs=op)

app.launch(debug=True,share=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
Running on public URL: https://0a86948f63a6b93ed1.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# XGBOOST

In [38]:
import xgboost as xgb

In [39]:
d_train=xgb.DMatrix(x_train,y_train)
d_test=xgb.DMatrix(x_test,y_test)

In [40]:
xgb_classifier=xgb.XGBClassifier(n_estimators=100,tree_method='hist')

In [43]:
xgb_classifier.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [44]:
y_pred_xgb_train=xgb_classifier.predict(x_train)
y_pred_xgb_test=xgb_classifier.predict(x_test)

In [45]:
report(y_train,y_pred_xgb_train)
report(y_test,y_pred_xgb_test)

Accuracy of the model :  1.0
[[402   0   0   0]
 [  0 391   0   0]
 [  0   0 406   0]
 [  0   0   0 401]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       402
           1       1.00      1.00      1.00       391
           2       1.00      1.00      1.00       406
           3       1.00      1.00      1.00       401

    accuracy                           1.00      1600
   macro avg       1.00      1.00      1.00      1600
weighted avg       1.00      1.00      1.00      1600

Accuracy of the model :  0.925
[[96  2  0  0]
 [11 95  3  0]
 [ 0  4 85  5]
 [ 0  0  5 94]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.94        98
           1       0.94      0.87      0.90       109
           2       0.91      0.90      0.91        94
           3       0.95      0.95      0.95        99

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.